# Generated by Django 3.1.4 on 2020-12-04 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capitals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(default='state', max_length=150)),
                ('captial', models.CharField(default='capital', max_length=200)),
            ],
        ),
    ]
